### ISSUE TITLE
Build CI&CD pipeline

### ISSUE THREAD

**Issue by tuanl2609** [secureIT-project/CVEfixes#1]
Hi,
I'm a cybersecurity student from Vietnam. My teacher wants me to make use of your dataset in DevSecOps and build a CI/CD pipeline. Do you have any ideas how I can do this? In what stage of a CI/CD pipeline should I use this dataset? And what tools do I need to use in that case? Can you help me out?
Sorry for my bad English. Your work and your dataset is very helpful. Thank you!

**Comment by leonmoonen** [comment]
Hi,

Thanks for your interest in using CVEfixes. First off, I think it's good to mention that Github's issue handling system is not really the right place to ask for support questions like this one. The goal of the issue handling system is to report problems in the dataset or in the collection tool.  However, since we are here, I can give you some pointers to get started:

1.  I suggest that you read the paper that is included in the Doc directory (the PDF file), as it contains several suggestions on how the dataset can be used, discusses the limitations, and has pointers to relevant related work on, for example, building a vulnerability detector.

2. One possible application of CVEfixes a DevSecOps workflow would be to use the dataset to build/train a vulnerability detector, and use that detector to check code in the CI/CD pipeline. However, this is a considerable effort, so before you go and do that, I would suggest having a follow-up discussion with your teacher to find out what he wants the CI/CD pipeline to do, to make sure that you do not do a lot of work in the wrong direction.
